---
- name: Install Jenkins, Docker, Trivy, AWS CLI, Helm, and Kubectl
  hosts: all
  become: true

  vars:
    jenkins_repo_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    trivy_key_url: https://aquasecurity.github.io/trivy-repo/deb/public.key
    trivy_repo: "deb https://aquasecurity.github.io/trivy-repo/deb {{ ansible_lsb.codename }} main"

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - fontconfig
          - openjdk-17-jre
          - wget
          - apt-transport-https
          - gnupg
          - lsb-release
          - snapd
        state: present

    - name: Download Jenkins key
      get_url:
        url: "{{ jenkins_repo_key_url }}"
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        filename: jenkins
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Start and enable Jenkins
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Add Jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
        enabled: yes

    - name: Restart Jenkins
      systemd:
        name: jenkins
        state: restarted
        enabled: yes

    - name: Add Trivy apt key
      apt_key:
        url: "{{ trivy_key_url }}"
        state: present

    - name: Add Trivy repository
      apt_repository:
        repo: "{{ trivy_repo }}"
        filename: trivy
        state: present

    - name: Install Trivy
      apt:
        name: trivy
        state: present
        update_cache: yes

    - name: Install AWS CLI via snap
      snap:
        name: aws-cli
        classic: yes
        state: present

    - name: Install Helm via snap
      snap:
        name: helm
        classic: yes
        state: present

    - name: Install kubectl via snap
      snap:
        name: kubectl
        classic: yes
        state: present
